"""add airQ

Revision ID: 6dd2adf928f9
Revises: ce5e6ca18347
Create Date: 2024-03-16 21:47:50.282018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd2adf928f9'
down_revision = 'ce5e6ca18347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('air_quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gaz', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('air_quality')
    # ### end Alembic commands ###
