"""empty message

Revision ID: 7afea179e308
Revises: 9c71e1743557
Create Date: 2024-03-16 22:54:32.657341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7afea179e308'
down_revision = '9c71e1743557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('air_quality', schema=None) as batch_op:
        batch_op.alter_column('gaz',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('pressure',
               existing_type=mysql.FLOAT(),
               nullable=False)

    with op.batch_alter_table('real_time_coordinates', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('altitude',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('DataTime',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('real_time_coordinates', schema=None) as batch_op:
        batch_op.alter_column('DataTime',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('altitude',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=mysql.FLOAT(),
               nullable=True)

    with op.batch_alter_table('air_quality', schema=None) as batch_op:
        batch_op.alter_column('pressure',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('gaz',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
