"""make OneToOne relation

Revision ID: 9c71e1743557
Revises: 6dd2adf928f9
Create Date: 2024-03-16 21:49:52.484095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c71e1743557'
down_revision = '6dd2adf928f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('real_time_coordinates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('air_quality_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'air_quality', ['air_quality_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('real_time_coordinates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('air_quality_id')

    # ### end Alembic commands ###
