"""Initial migration.

Revision ID: c8b7ac53d521
Revises: 
Create Date: 2024-03-16 20:28:40.006213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b7ac53d521'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('real_time_coordinates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heightFromGround', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('real_time_coordinates', schema=None) as batch_op:
        batch_op.drop_column('heightFromGround')

    # ### end Alembic commands ###
