"""make all fields nullable

Revision ID: e6755c91ab3a
Revises: a4ec9d50c5bb
Create Date: 2024-03-31 00:20:13.551632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6755c91ab3a'
down_revision = 'a4ec9d50c5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('air_quality', schema=None) as batch_op:
        batch_op.alter_column('gaz',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('carbon_monoxide_ratio',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('temp',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('pressure',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('humidity',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('air_quality',
               existing_type=mysql.FLOAT(),
               nullable=True)

    with op.batch_alter_table('real_time_coordinates', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('altitude',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('DataTime',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('real_time_coordinates', schema=None) as batch_op:
        batch_op.alter_column('DataTime',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('altitude',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=mysql.FLOAT(),
               nullable=False)

    with op.batch_alter_table('air_quality', schema=None) as batch_op:
        batch_op.alter_column('air_quality',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('humidity',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('pressure',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('temp',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('carbon_monoxide_ratio',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('gaz',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
